apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-core
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ldmcore.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ldmcore.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ldmcore.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.config.server.port }}
              protocol: TCP
          env:
            - name: SPRING_CONFIG_LOCATION
              value: /home/service/roboartisan/conf/ldm-core.yml
            - name: SERVICE_PORT
              value: "{{ .Values.config.server.port }}"
            - name: DATASOURCE_HOST
              value: "{{ .Values.global.config.mysql.host }}"
            - name: DATASOURCE_PORT
              value: "{{ .Values.global.config.mysql.port }}"
            - name: DATASOURCE_USERNAME
              value: "{{ .Values.global.config.mysql.username }}"
            - name: DATASOURCE_PASSWORD
              value: "{{ .Values.global.config.mysql.password }}"
            - name: DATASOURCE_NAME
              value: "{{ .Values.global.config.mysql.db }}"
            - name: LDMBASE_ENDPOINT
              value: "{{ .Values.global.config.ldm.base.endpoint }}"
            - name: LDMALG_ENDPOINT
              value: "{{ .Values.global.config.ldm.alg.endpoint }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: conf
              readOnly: true
              mountPath: /home/service/roboartisan/conf
      volumes:
        - name: conf
          configMap:
            name: ldm-core-config
            defaultMode: 420
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
