apiVersion: v1
kind: Service
metadata:
  name: ldm-alg
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ldmalg.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ldmalg.selectorLabels" . | nindent 4 }}
