image:
  repository: swr.cn-south-1.myhuaweicloud.com/robo/ldm-rcs
  tag: "202305101044"

imagePullSecrets:
  - name: default-secret

resources:
  limits:
    cpu: 0.5
    memory: 2Gi
  requests:
    cpu: 0.25
    memory: 512Mi

config:
  mysql:
    host: 127.0.0.1
    username: root
    password: ""
    port: 3306
    db: ldm
  ldm:
    base:
      endpoint: http://ldm-base:60000
    core:
      endpoint: http://ldm-core:60001
