global:
  imagePullSecrets: ["default-secret"]
  storageClass: "csi-disk"
  redis:
    password: ""

image:
  registry: swr.cn-south-1.myhuaweicloud.com
  repository: robo/redis
  tag: 7.0.11-debian-11-r0

fullnameOverride: "redis"


# 定义集群的模式  Allowed values: `standalone` or `replication`
architecture: replication


# redis 服务配置定义
commonConfiguration: |-
  # Enable AOF https://redis.io/topics/persistence#append-only-file
  appendonly yes
  # Disable RDB persistence, AOF persistence already enabled.
  save ""


# master 节点配置信息
master:
  containerPorts:
    redis: 6379

  kind: StatefulSet

  readinessProbe:
    enabled: true

  persistence:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 8Gi

  service:
    type: ClusterIP
    ports:
      redis: 6379


# replica 节点配置信息
replica:
  replicaCount: 1
  containerPorts:
    redis: 6379

  persistence:
    enabled: true
    storageClass: ""
    accessModes:
      - ReadWriteOnce
    size: 8Gi

  service:
    type: ClusterIP
    ports:
      redis: 6379


# sentinel 节点配置信息
sentinel:
  enabled: false
  containerPorts:
    sentinel: 26379

  persistence:
    enabled: true
    storageClass: ""
    accessModes:
      - ReadWriteOnce
    size: 100Mi

  service:
    type: ClusterIP
    ports:
      redis: 6379
      sentinel: 26379